### ISSUE TITLE
Tweak axis order for every system

### ISSUE THREAD

**Issue by sbourgoing** [SqueezeStudioAnimation/dpAutoRigSystem#1]
We want to prevent the gimbal problem as much as we can. One solution for this problem is to tweak all axis order and ensure the gimbal happen on the less used axis.

**Comment by sbourgoing** [comment]
This is an issue test for dpAutoRigSystem with notification. We will need to integrate those changes in Danilo version 
@SqueezeStudioAnimation/dev 

Let me know if notification are working correctly !

**Comment by nilouco** [comment]
Thanks.

## 

Danilo Pinheiro
Rigging - R&D
+1 418 271-3921
nilouco.blogspot.com

**Comment by sbourgoing** [comment]
Shotgun --> https://squeeze.shotgunstudio.com/page/10342#Ticket_1544_Global%20-%20Tweak%20Axis%20Order
