### ISSUE TITLE
Prevent crash on Extra tool loading

### ISSUE THREAD

**Issue by sbourgoing** [SqueezeStudioAnimation/dpAutoRigSystem#28]
We need to find a way to prevent the auto-rig top crash when a module is not loaded correctly. The tool would load with what he can and could shoot an error that inform the user about which one didn't load correctly.

Since some person us it, we need to have a better error handling to be able to find problems faster.

**Comment by renaudll** [comment]
Done! Any guide loaded via createGuideButton() is now sandboxed in a try/except statement.
